### PR TITLE
ECAD-generated Kicad library support & fuller kicad part annotation

### PR DESCRIPTION
**Pull request by rtpavlovsk21**
Revision of #194. This adds:
1. an example file in ```test_data``` that is an example of how ECAD parts exist when downloaded from part providers (Mouser, Digikey, etc) 
2. a test that checks if the ecad parts have no pins
3. a method to construct the rest of the ```Part``` attribute space, when additional properties are available in the kicad symbol libraries. it attempts to avoid overwriting existing ```Part``` attributes.

### CODE REVIEW

**Comment by rtpavlovsk21** [comment]
I'll close this in a few days, and will host it on my fork.

**Comment by devbisme** [comment]
I'm actually integrating it into my development branch. Your PR exposed an error in how I was parsing the parts for KiCad 6 and 7: parts can have pins outside of units. So I am implementing that. (Just looking for pins if there aren't any units isn't really the right way to do it.) So, eventually, much of this PR will make it into my version of SKiDL.

**Comment by devbisme** [comment]
Take a look and see if it does what you need it to.

**Comment by rtpavlovsk21** [comment]
Thanks @devbisme! I will have a look this weekend.

**Pull request merged**
