### PR TITLE
adding elements that import simple properties contained in kicad7 lib…

### PR DESCRIPTION
**Pull request by rtpavlovsk21**
…raries. 

This PR would substantially change the ```Part``` attribute space. It attempts to load more of the properties that are included in kicad7 libraries that are currently discarded.

I am starting this pull-request early to feel out if this valued. 

There would need to be at least some examples / tests to complete this PR.

### CODE REVIEW

**Comment by devbisme** [comment]
Thanks for the PR! I've looked at it and I have a few questions:
1. Why issue a warning if `KICAD7_SYMBOL_DIR` is found and added to the default libraries?
2. Pins are currently added to the part in the `parse_lib_part` function instead of the `load_sch_lib` function. For libraries with a lot of parts, this reduces the processing time since pins are only parsed when a part is actually used. In addition, you would need to assign pins to units in the part if it is a multi-unit part, and correctly setup pin attributes, etc. Is there some advantage to placing this in the `load_sch_lib` function?
3. What new properties are added to KiCad 7 parts and how would they be used in SKiDL? The output from SKiDL is a netlist that goes to PCBNEW. Are any of these new properties used in the netlist?

**Comment by rtpavlovsk21** [comment]
Thanks @devbisme these are good questions and points. I agree that the per-part parsing is more efficient and better overall.

My additions are likely not in the right place, but I still feel that the pins are not parsed in the ```parse_lib_part``` function either. Perhaps this is a simple key-error related to the fact that ```units``` returns empty. https://github.com/devbisme/skidl/blob/441bb43fea289e0ad7955783cd67ba95bda53152/src/skidl/tools/kicad7/lib.py#L295-L310

Here is an example part:
```XML
(kicad_symbol_lib (version 20211014) (generator SamacSys_ECAD_Model)
  (symbol "RJMG20162141BER" (in_bom yes) (on_board yes)
    (property "Reference" "J" (at 26.67 7.62 0)
      (effects (font (size 1.27 1.27)) (justify left top))
    )
    (property "Value" "RJMG20162141BER" (at 26.67 5.08 0)
      (effects (font (size 1.27 1.27)) (justify left top))
    )
    (property "Footprint" "RJMG20162141BER" (at 26.67 -94.92 0)
      (effects (font (size 1.27 1.27)) (justify left top) hide)
    )
    (property "Datasheet" "https://componentsearchengine.com/Datasheets/1/RJMG20162141BER.pdf" (at 26.67 -194.92 0)
      (effects (font (size 1.27 1.27)) (justify left top) hide)
    )
    (property "ki_description" "Modular Connectors / Ethernet Connectors R/A,DipType,ShortBod 1000 baseT,GY/GY" (at 26.67 -294.92 0)
      (effects (font (size 1.27 1.27)) (justify left top) hide)
    )
    (property "Height" "13.9" (at 26.67 -394.92 0)
      (effects (font (size 1.27 1.27)) (justify left top) hide)
    )
    (property "Mouser Part Number" "523-RJMG20162141BER" (at 26.67 -494.92 0)
      (effects (font (size 1.27 1.27)) (justify left top) hide)
    )
    (property "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Amphenol-Commercial-Products/RJMG20162141BER?qs=AVT0UMTfAuItaMrM1bOyzg%3D%3D" (at 26.67 -594.92 0)
      (effects (font (size 1.27 1.27)) (justify left top) hide)
    )
    (property "Manufacturer_Name" "Amphenol" (at 26.67 -694.92 0)
      (effects (font (size 1.27 1.27)) (justify left top) hide)
    )
    (property "Manufacturer_Part_Number" "RJMG20162141BER" (at 26.67 -794.92 0)
      (effects (font (size 1.27 1.27)) (justify left top) hide)
    )
    (rectangle
      (start 5.08 2.54)
      (end 25.4 -20.32)
      (stroke (width 0.254) (type default))
      (fill (type background))
    )
    (pin passive line (at 0 0 0) (length 5.08)
      (name "GND" (effects (font (size 1.27 1.27))))
      (number "1" (effects (font (size 1.27 1.27))))
    )
....
```

Maybe the pin parsing just needs updated.

The goals I had were two fold: 1. get pin definitions and 2. maintain the property elements in the kicad library, accessible from ```skidl.Part```. Perhaps some kind of key-filter method similar to my initial PR could be used to prevent overwriting core ```skidl``` properties or existing part attributes. 

My plan:
1. Look at the kicad links in ```parse_lib_part``` function header
2. Write some tests for parsing kicad7 format, maybe even understanding if there are lib-version keys that could be used to detect if the parser is appropriate (ex```kicad_symbol_lib (version 20211014)```). Add some tests based on some imaginary parts.
3. Ideally preserve all kicad7 ```property``` elements as attributes of the part in key-value pairs.
4. (optional, and sounds hard) find a way to store unparsed information in the ```skidl.Part``` that doesn't ruin the parse-on-getattr logic.

**Comment by devbisme** [comment]
If the pins aren't being added to the Part object, then that's a fault in the `parse_lib_part` function. I'll fix that in the development branch. (This will include adding more KiCad 7 testing, which should help you.) Then you can start incrementally adding your other modifications to that and we'll see which ones we like.

**Comment by devbisme** [comment]
I expanded the tests in `test_lib.py` and they didn't detect any new errors when processing KiCad 6 or 7 libraries. I also tested in ipython and things seems to run correctly. All the pins are there when a part is instantiated, including all its units. Can you send me what you did so I can replicate the problem?

**Pull request closed without merging**
